name: Pytest
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.5.x', '3.6.x', '3.7.x', '3.8.x', '3.9.x', '3.10.x', '3.x']
    name: Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.5.x -> 3.x
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Install requierments
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: pytest -vv